import React, { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Star, ShieldCheck, HeartHandshake, ExternalLink, Smartphone, Award } from 'lucide-react';
import confetti from 'canvas-confetti';
import { useFeedback } from '../../context/FeedbackContext';
import { generateReviewText } from '../../utils/reviewGenerator';
import { getActiveProviders } from '../../utils/providerRouter';
import { KeywordChips } from './KeywordChips';
import { AutoReviewEditor } from './AutoReviewEditor';
import { ThankYouCard } from './ThankYouCard';
import { copyToMobileClipboard } from '../../utils/clipboardHelper';

const SENTIMENT_CONFIG = {
  5: { label: 'Absolute Perfection! 🌟', color: '#059669', bg: '#ecfdf5', border: '#a7f3d0', shadow: 'rgba(16, 185, 129, 0.25)' },
  4: { label: 'Great Experience! 😊', color: '#0284c7', bg: '#f0f9ff', border: '#bae6fd', shadow: 'rgba(2, 132, 199, 0.25)' },
  3: { label: 'Okay / Average 😐', color: '#d97706', bg: '#fffbeb', border: '#fde68a', shadow: 'rgba(245, 158, 11, 0.25)' },
  2: { label: 'Needs Improvement 😕', color: '#e11d48', bg: '#fff1f2', border: '#fecdd3', shadow: 'rgba(225, 29, 72, 0.25)' },
  1: { label: 'Unsatisfactory 😞', color: '#dc2626', bg: '#fef2f2', border: '#fca5a5', shadow: 'rgba(220, 38, 38, 0.25)' },
};

export function GuestReviewCard() {
  const [searchParams] = useSearchParams();
  const roomParam = searchParams.get('room') || searchParams.get('table') || '';
  const guestParam = searchParams.get('guest') || '';

  const { settings, keywords, addFeedback, checkIsDuplicate } = useFeedback();

  const [rating, setRating] = useState(5);
  const [selectedTags, setSelectedTags] = useState([]);
  const [customNote, setCustomNote] = useState('');
  const [tone, setTone] = useState(settings?.tone || 'friendly');
  const [guestContact, setGuestContact] = useState('');
  const [roomNumber] = useState(roomParam);

  const [submitted, setSubmitted] = useState(false);

  const primaryColor = settings?.themeColor || '#4f46e5';
  const isHighRating = rating >= 4;
  const activeProviders = getActiveProviders(settings);
  const isDuplicate = checkIsDuplicate(guestContact);

  const currentSentiment = SENTIMENT_CONFIG[rating] || SENTIMENT_CONFIG[5];

  // Auto-generate review text
  const autoGeneratedReviewText = generateReviewText({
    rating,
    selectedTags,
    customNote: '',
    hotelName: settings?.hotelName || 'Sree Jee Stay',
    tone,
    reviewLength: settings?.reviewLength || 'short',
    includeEmojis: settings?.includeEmojis !== false,
    mentionStaff: settings?.mentionStaff !== false,
    mentionCleanliness: settings?.mentionCleanliness !== false,
    mentionFood: settings?.mentionFood !== false,
    mentionLocation: settings?.mentionLocation !== false,
    keywordsList: keywords,
  });

  // Effective review text shown to user (custom edited or auto generated)
  const reviewText = customNote !== '' ? customNote : autoGeneratedReviewText;

  const toggleTag = (tagId) => {
    setSelectedTags((prev) =>
      prev.includes(tagId) ? prev.filter((t) => t !== tagId) : [...prev, tagId]
    );
    setCustomNote(''); // Reset custom override so new tags update the text
  };

  const handleRefreshPhrasing = () => {
    setCustomNote(''); // Regenerate natural variation
  };

  const handlePostToProvider = async (provider) => {
    if (isDuplicate) return;

    // 1. Copy review text to mobile clipboard synchronously
    await copyToMobileClipboard(reviewText);

    // 2. Submit feedback internally
    addFeedback({
      roomNumber: roomNumber || 'Guest',
      rating,
      tags: selectedTags,
      reviewText,
      guestContact,
      postedPublic: true,
    });

    // 3. Trigger confetti celebration for 4-5 stars
    if (isHighRating) {
      try {
        confetti({
          particleCount: 100,
          spread: 75,
          origin: { y: 0.6 },
        });
      } catch (e) {}
    }

    setSubmitted(true);

    // 4. Open destination review provider
    if (provider?.url) {
      window.open(provider.url, '_blank', 'noopener,noreferrer');
    }
  };

  const handleSubmitPrivateFeedback = async (e) => {
    if (e) e.preventDefault();
    if (isDuplicate) return;

    addFeedback({
      roomNumber: roomNumber || 'Guest',
      rating,
      tags: selectedTags,
      reviewText,
      guestContact,
      postedPublic: false,
    });

    setSubmitted(true);
  };

  if (submitted) {
    return (
      <ThankYouCard
        rating={rating}
        guestContact={guestContact}
        onReset={() => {
          setSubmitted(false);
          setRating(5);
          setSelectedTags([]);
          setCustomNote('');
        }}
      />
    );
  }

  return (
    <div
      className="guest-card"
      style={{
        maxWidth: '480px',
        width: '100%',
        margin: '1.25rem auto',
        background: '#ffffff',
        borderRadius: '28px',
        padding: '1.75rem 1.35rem',
        boxShadow: `0 20px 45px -10px ${currentSentiment.shadow}, 0 0 0 1px ${currentSentiment.border}`,
        border: `1.5px solid ${currentSentiment.border}`,
        textAlign: 'center',
        boxSizing: 'border-box',
        transition: 'all 0.35s cubic-bezier(0.16, 1, 0.3, 1)',
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Dynamic Ambient Background Glow */}
      <div
        style={{
          position: 'absolute',
          top: '-60px',
          left: '50%',
          transform: 'translateX(-50%)',
          width: '260px',
          height: '140px',
          background: `radial-gradient(circle, ${currentSentiment.border} 0%, transparent 70%)`,
          opacity: 0.6,
          pointerEvents: 'none',
          zIndex: 0,
        }}
      />

      <div style={{ position: 'relative', zIndex: 1 }}>
        {/* HERO BRANDING HEADER */}
        <div style={{ marginBottom: '1.25rem' }}>
          {settings?.logoUrl ? (
            <img
              src={settings.logoUrl}
              alt="Hotel Logo"
              style={{
                width: '76px',
                height: '76px',
                borderRadius: '50%',
                margin: '0 auto 0.75rem',
                objectFit: 'cover',
                border: '3px solid #ffffff',
                boxShadow: '0 8px 20px rgba(0,0,0,0.1)',
              }}
            />
          ) : (
            <div
              style={{
                width: '76px',
                height: '76px',
                borderRadius: '50%',
                background: `linear-gradient(135deg, ${primaryColor} 0%, #312e81 100%)`,
                color: 'white',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '2rem',
                fontWeight: 900,
                margin: '0 auto 0.75rem',
                boxShadow: '0 8px 24px rgba(79, 70, 229, 0.25)',
                border: '3px solid #ffffff',
              }}
            >
              {(settings?.hotelName || 'Sree Jee Stay')[0]}
            </div>
          )}

          {/* Hotel Name & Badges */}
          <h1 style={{ fontSize: '1.45rem', fontWeight: 900, color: '#0f172a', margin: '0 0 0.35rem', letterSpacing: '-0.02em' }}>
            {settings?.hotelName || 'Sree Jee Stay'}
          </h1>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '0.65rem' }}>
            <span style={{ fontSize: '0.75rem', fontWeight: 800, color: '#059669', background: '#ecfdf5', padding: '0.2rem 0.6rem', borderRadius: '12px', border: '1px solid #a7f3d0', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              <ShieldCheck size={13} /> Official Guest Review
            </span>

            <span style={{ fontSize: '0.75rem', fontWeight: 800, color: '#1e40af', background: '#eff6ff', padding: '0.2rem 0.6rem', borderRadius: '12px', border: '1px solid #bfdbfe', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              <Award size={13} /> 4.9 ★ Exceptional
            </span>
          </div>

          {/* Optional Room Prefill Notice */}
          {roomNumber && (
            <div style={{ fontSize: '0.775rem', color: '#475569', fontWeight: 700, background: '#f8fafc', padding: '0.35rem 0.75rem', borderRadius: '14px', border: '1px solid #e2e8f0', display: 'inline-flex', alignItems: 'center', gap: '0.3rem' }}>
              <span>🏨</span> Welcome {guestParam ? `${guestParam} (` : ''}Room {roomNumber}{guestParam ? ')' : ''}!
            </div>
          )}
        </div>

        {/* 5-STAR RATING SELECTOR */}
        <div style={{ marginBottom: '1.25rem' }}>
          <div style={{ fontSize: '0.875rem', fontWeight: 800, color: '#334155', marginBottom: '0.65rem' }}>
            How was your stay experience?
          </div>

          <div style={{ display: 'flex', justifyContent: 'center', gap: '0.45rem', marginBottom: '0.65rem' }}>
            {[1, 2, 3, 4, 5].map((star) => {
              const isActive = star <= rating;
              return (
                <button
                  key={star}
                  type="button"
                  onClick={() => {
                    setRating(star);
                    setSelectedTags([]);
                    setCustomNote('');
                  }}
                  style={{
                    background: 'transparent',
                    border: 'none',
                    cursor: 'pointer',
                    padding: '0.2rem',
                    transition: 'transform 0.2s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
                    transform: isActive ? 'scale(1.12)' : 'scale(1)',
                  }}
                >
                  <Star
                    size={38}
                    color={isActive ? (rating >= 4 ? '#f59e0b' : '#f97316') : '#cbd5e1'}
                    fill={isActive ? (rating >= 4 ? '#f59e0b' : '#f97316') : 'none'}
                    style={{
                      filter: isActive ? 'drop-shadow(0 4px 8px rgba(245, 158, 11, 0.4))' : 'none',
                    }}
                  />
                </button>
              );
            })}
          </div>

          {/* SENTIMENT MOOD BADGE */}
          <div
            style={{
              display: 'inline-block',
              background: currentSentiment.bg,
              color: currentSentiment.color,
              border: `1px solid ${currentSentiment.border}`,
              padding: '0.35rem 0.85rem',
              borderRadius: '20px',
              fontSize: '0.85rem',
              fontWeight: 800,
              boxShadow: `0 4px 12px ${currentSentiment.shadow}`,
              transition: 'all 0.25s ease',
            }}
          >
            {currentSentiment.label}
          </div>
        </div>

        {/* KEYWORD TAG CHIPS */}
        <KeywordChips
          rating={rating}
          selectedTags={selectedTags}
          onToggleTag={toggleTag}
        />

        {/* AUTO-GENERATED AI REVIEW EDITOR */}
        <AutoReviewEditor
          rating={rating}
          reviewText={reviewText}
          onTextChange={(val) => setCustomNote(val)}
          onRefreshPhrasing={handleRefreshPhrasing}
          currentTone={tone}
          onChangeTone={(t) => {
            setTone(t);
            setCustomNote('');
          }}
        />

        {/* PHONE / CUSTOMER ID VERIFICATION INPUT */}
        <div style={{ margin: '1.15rem 0 0.85rem 0', textAlign: 'left' }}>
          <label
            style={{
              fontSize: '0.78rem',
              fontWeight: 800,
              color: '#334155',
              display: 'flex',
              alignItems: 'center',
              gap: '0.35rem',
              marginBottom: '0.35rem',
            }}
          >
            <Smartphone size={14} color="#4f46e5" />
            <span>Phone / Room / Customer ID (Anti-Duplicate Check):</span>
          </label>
          <input
            type="text"
            className="form-input"
            value={guestContact}
            onChange={(e) => setGuestContact(e.target.value)}
            placeholder="e.g. 9876543210 or Room 204"
            style={{
              width: '100%',
              fontSize: '0.875rem',
              padding: '0.65rem 0.85rem',
              borderRadius: '12px',
              border: isDuplicate ? '1.5px solid #fca5a5' : '1px solid #cbd5e1',
              background: isDuplicate ? '#fff1f2' : '#ffffff',
              boxSizing: 'border-box',
            }}
          />
          {isDuplicate && (
            <div style={{ fontSize: '0.75rem', color: '#dc2626', fontWeight: 700, marginTop: '0.35rem' }}>
              ⚠️ A review has already been submitted for this Phone / ID.
            </div>
          )}
        </div>

        {/* ACTION BUTTONS / PLATFORM ROUTERS */}
        <div style={{ marginTop: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.65rem' }}>
          {isHighRating ? (
            <>
              {activeProviders.map((provider) => (
                <button
                  key={provider.type}
                  type="button"
                  className="btn-primary-action"
                  onClick={() => handlePostToProvider(provider)}
                  disabled={isDuplicate}
                  style={{
                    padding: '0.9rem 1.25rem',
                    borderRadius: '16px',
                    fontSize: '0.95rem',
                    fontWeight: 800,
                    background: primaryColor,
                    justifyContent: 'center',
                    boxShadow: '0 8px 22px rgba(79, 70, 229, 0.28)',
                    opacity: isDuplicate ? 0.6 : 1,
                    cursor: isDuplicate ? 'not-allowed' : 'pointer',
                  }}
                >
                  <ExternalLink size={18} />
                  <span>Post Review on {provider.name}</span>
                </button>
              ))}

              <div style={{ fontSize: '0.725rem', color: '#64748b', fontWeight: 600 }}>
                📋 Tapping above auto-copies your review text to your phone clipboard!
              </div>
            </>
          ) : (
            <button
              type="button"
              className="btn-primary-action"
              onClick={handleSubmitPrivateFeedback}
              disabled={isDuplicate}
              style={{
                padding: '0.9rem 1.25rem',
                borderRadius: '16px',
                fontSize: '0.95rem',
                fontWeight: 800,
                background: '#dc2626',
                justifyContent: 'center',
                boxShadow: '0 8px 22px rgba(220, 38, 38, 0.25)',
                opacity: isDuplicate ? 0.6 : 1,
                cursor: isDuplicate ? 'not-allowed' : 'pointer',
              }}
            >
              <HeartHandshake size={18} />
              <span>Submit Private Feedback to Duty Manager</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
