import React, { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Star, ShieldCheck, ExternalLink, Smartphone, HeartHandshake, Lock } from 'lucide-react';
import confetti from 'canvas-confetti';
import { motion } from 'framer-motion';
import { useFeedback } from '../../context/FeedbackContext';
import { generateReviewText } from '../../utils/reviewGenerator';
import { getActiveProviders } from '../../utils/providerRouter';
import { KeywordChips } from './KeywordChips';
import { AutoReviewEditor } from './AutoReviewEditor';
import { ThankYouCard } from './ThankYouCard';
import { copyToMobileClipboard } from '../../utils/clipboardHelper';

const RATING_DESCRIPTIONS = {
  5: "Wonderful. We're glad you enjoyed your stay.",
  4: "Very Good. Thank you for your feedback.",
  3: "Good. We appreciate your feedback.",
  2: "Fair. Tell us how we can improve.",
  1: "We're sorry your stay fell short. Please let us know.",
};

export function GuestReviewCard() {
  const [searchParams] = useSearchParams();
  const roomParam = searchParams.get('room') || searchParams.get('table') || '';

  const { settings, keywords, addFeedback, checkIsDuplicate, setActiveTab } = useFeedback();

  const [rating, setRating] = useState(5);
  const [hoverRating, setHoverRating] = useState(0);
  const [selectedTags, setSelectedTags] = useState([]);
  const [customNote, setCustomNote] = useState('');
  const [tone, setTone] = useState(settings?.tone || 'friendly');
  const [guestContact, setGuestContact] = useState('');
  const [roomNumber] = useState(roomParam);
  const [variationSeed, setVariationSeed] = useState(() => Math.random());
  const [submitted, setSubmitted] = useState(false);

  const hotelName = settings?.hotelName || settings?.name || 'Boutique Hotel';
  const logoUrl = settings?.logoUrl || '';
  const brandColor = settings?.themeColor || '#1C1917';
  const locationText = settings?.location || 'Rajasthan · India';
  const isHighRating = rating >= 4;
  const activeProviders = getActiveProviders(settings);
  const isDuplicate = checkIsDuplicate(guestContact);

  // Dynamic review text generation
  const autoGeneratedReviewText = generateReviewText({
    rating,
    selectedTags,
    customNote: '',
    hotelName,
    tone,
    reviewLength: settings?.reviewLength || 'short',
    includeEmojis: settings?.includeEmojis !== false,
    keywordsList: keywords,
    variationSeed,
  });

  const reviewText = customNote !== '' ? customNote : autoGeneratedReviewText;

  const toggleTag = (tagId) => {
    setSelectedTags((prev) =>
      prev.includes(tagId) ? prev.filter((t) => t !== tagId) : [...prev, tagId]
    );
    setCustomNote('');
    setVariationSeed(Math.random());
  };

  const handleRefreshPhrasing = () => {
    setCustomNote('');
    setVariationSeed(Math.random());
  };

  const handlePostToProvider = async (provider) => {
    if (isDuplicate) return;

    // 1. Copy review text to clipboard
    await copyToMobileClipboard(reviewText);

    // 2. Submit feedback internally
    addFeedback({
      roomNumber: roomNumber || 'Guest',
      rating,
      tags: selectedTags,
      reviewText,
      guestContact,
      postedPublic: true,
    });

    // 3. Subtle celebratory confetti for positive rating
    if (isHighRating) {
      try {
        confetti({
          particleCount: 65,
          spread: 60,
          origin: { y: 0.6 },
          colors: ['#F59E0B', '#D97706', '#E11D48', '#10B981'],
        });
      } catch (e) {}
    }

    setSubmitted(true);

    // 4. Open destination provider popup
    if (provider?.url) {
      window.open(provider.url, '_blank', 'noopener,noreferrer');
    }
  };

  const handleSubmitPrivateFeedback = async (e) => {
    if (e) e.preventDefault();
    if (isDuplicate) return;

    addFeedback({
      roomNumber: roomNumber || 'Guest',
      rating,
      tags: selectedTags,
      reviewText,
      guestContact,
      postedPublic: false,
    });

    setSubmitted(true);
  };

  if (submitted) {
    return (
      <ThankYouCard
        rating={rating}
        guestContact={guestContact}
        onReset={() => {
          setSubmitted(false);
          setRating(5);
          setSelectedTags([]);
          setCustomNote('');
        }}
      />
    );
  }

  const displayedRating = hoverRating || rating;

  return (
    <div className="guest-page-wrapper">
      <div className="guest-container">
        <motion.div
          className="guest-luxury-card"
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.28, ease: [0.16, 1, 0.3, 1] }}
        >
          {/* 1. HERO HOTEL IDENTITY */}
          <div style={{ marginBottom: '1.5rem' }}>
            {logoUrl ? (
              <img
                src={logoUrl}
                alt={hotelName}
                className="hotel-hero-logo"
              />
            ) : (
              <div
                className="hotel-hero-monogram"
                style={{ background: brandColor }}
              >
                {hotelName.charAt(0).toUpperCase()}
              </div>
            )}

            <h1 className="hotel-hero-title">
              {hotelName}
            </h1>

            <div className="hotel-hero-location">
              {locationText}
            </div>

            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', flexWrap: 'wrap' }}>
              <span className="hotel-badge-verified">
                <ShieldCheck size={13} />
                <span>Verified Guest Experience</span>
              </span>

              {roomNumber && (
                <span
                  style={{
                    fontSize: '0.75rem',
                    fontWeight: 600,
                    color: '#78716C',
                    background: '#F5F5F4',
                    padding: '0.25rem 0.65rem',
                    borderRadius: 'var(--radius-full)',
                  }}
                >
                  Room {roomNumber}
                </span>
              )}
            </div>
          </div>

          {/* 2. ELEGANT STAR RATING INTERACTION */}
          <div className="guest-rating-section">
            <div className="guest-rating-heading">
              How was your stay?
            </div>
            <div className="guest-rating-subtext">
              Your experience matters to us.
            </div>

            <div className="guest-star-row" onMouseLeave={() => setHoverRating(0)}>
              {[1, 2, 3, 4, 5].map((star) => {
                const isFilled = star <= displayedRating;
                return (
                  <button
                    key={star}
                    type="button"
                    className="guest-star-btn"
                    onMouseEnter={() => setHoverRating(star)}
                    onClick={() => {
                      setRating(star);
                      setSelectedTags([]);
                      setCustomNote('');
                      setVariationSeed(Math.random());
                    }}
                    aria-label={`Rate ${star} star`}
                  >
                    <Star
                      size={36}
                      color={isFilled ? 'var(--gold-star)' : 'var(--gold-star-idle)'}
                      fill={isFilled ? 'var(--gold-star)' : 'transparent'}
                      strokeWidth={1.5}
                    />
                  </button>
                );
              })}
            </div>

            <div className="guest-rating-feedback-label">
              {RATING_DESCRIPTIONS[displayedRating] || "Wonderful. We're glad you enjoyed your stay."}
            </div>
          </div>

          {/* 3. HIGHLIGHTS & AMENITIES SELECTION */}
          <KeywordChips
            rating={rating}
            selectedTags={selectedTags}
            onToggleTag={toggleTag}
          />

          {/* 4. WRITTEN REVIEW (GUESTBOOK EXPERIENCE) */}
          <AutoReviewEditor
            rating={rating}
            reviewText={reviewText}
            onTextChange={(val) => setCustomNote(val)}
            onRefreshPhrasing={handleRefreshPhrasing}
          />

          {/* 5. GUEST IDENTIFIER & RESERVATION FIELD */}
          <div style={{ margin: '1.5rem 0', textAlign: 'left' }}>
            <label
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '0.35rem',
                fontFamily: 'var(--font-sans)',
                fontSize: '0.8125rem',
                fontWeight: 600,
                color: '#44403C',
                marginBottom: '0.35rem',
              }}
            >
              <Smartphone size={14} color="#78716C" />
              <span>Phone or Room Number (Verification):</span>
            </label>
            <input
              type="text"
              className="saas-input"
              value={guestContact}
              onChange={(e) => setGuestContact(e.target.value)}
              placeholder="e.g. 9876543210 or Room 204"
              style={{
                borderColor: isDuplicate ? '#DC2626' : '#E7E5E4',
                background: isDuplicate ? '#FFF1F2' : '#FFFFFF',
              }}
            />
            {isDuplicate && (
              <div style={{ fontSize: '0.75rem', color: '#DC2626', fontWeight: 500, marginTop: '0.25rem' }}>
                A review has already been recorded for this identifier.
              </div>
            )}
          </div>

          {/* 6. PRIMARY SUBMIT CTA */}
          <div style={{ marginTop: '1.75rem' }}>
            {isHighRating ? (
              <>
                {activeProviders.map((provider) => (
                  <button
                    key={provider.type}
                    type="button"
                    className="guest-submit-cta"
                    onClick={() => handlePostToProvider(provider)}
                    disabled={isDuplicate}
                    style={{
                      background: brandColor,
                      color: '#FFFFFF',
                    }}
                  >
                    <ExternalLink size={16} />
                    <span>Submit Your Review on {provider.name}</span>
                  </button>
                ))}
                <div style={{ fontSize: '0.75rem', color: '#78716C', fontWeight: 500, marginTop: '0.5rem' }}>
                  Review text is automatically copied to your clipboard upon tapping.
                </div>
              </>
            ) : (
              <button
                type="button"
                className="guest-submit-cta"
                onClick={handleSubmitPrivateFeedback}
                disabled={isDuplicate}
                style={{
                  background: '#DC2626',
                  color: '#FFFFFF',
                }}
              >
                <HeartHandshake size={16} />
                <span>Submit Feedback to Duty Manager</span>
              </button>
            )}
          </div>
        </motion.div>
      </div>
    </div>
  );
}
